# Generated by Django 3.2.5 on 2021-07-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='phone',
            field=models.IntegerField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
